"""
AlgoBot -- Live Signal Engine
==============================
Module:  src/execution/live_signal_engine.py
Phase:   6 -- Paper Trading
Purpose: Real-time ORB and FHB signal detection using IBKR historical data.
         Reuses compute_orb_signals() and compute_fhb_signals() so that live
         signals are generated by exactly the same logic as the backtests.

Architecture:
    IBKR historical bars (5-min, 1-hour, useRTH=True)
        -> compute_orb_signals() / compute_fhb_signals()
        -> apply same gates as simulate_fhb_trades()
        -> return signal dict for IBKRBridge.submit_signal()

Schedule:
    09:45 ET  -- ORB check (opening range 09:30-09:45 is complete)
    10:30 ET  -- FHB check (first hour 09:30-10:30 is complete)
    16:00 ET  -- EOD cleanup

Signal dict returned:
    {
        "market":    "ES",
        "direction": "LONG",
        "entry":     5820.25,
        "stop":      5802.00,
        "target":    5856.75,
        "size_mult": 1.0,        # 0.5 = half size (delta/GLS partial gate)
        "strategy":  "ORB",      # or "FHB"
        "gls_score": 72,
        "of_score":  2,
    }
"""

from __future__ import annotations

import sys
import calendar
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

import pandas as pd
import pytz

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

try:
    from ib_insync import IB, Future
    IB_AVAILABLE = True
except ImportError:
    IB_AVAILABLE = False

from src.strategy.orb_signal import compute_orb_signals
from src.utils.data_downloader import download_market
from src.strategy.indicators import calculate_indicators, add_atr_baseline
from src.strategy.regime_classifier import classify_regimes
from src.strategy.htf_bias import add_htf_bias
from src.utils.logger import get_logger

# Import FHB functions from the backtest script
from run_fhb_backtest import (
    compute_fhb_signals,
    compute_1h_atr,
    FHB_ATR_PERIOD,
    FHB_ATR_STOP_MULT,
    FHB_GLS_MIN_SCORE,
    FHB_GLS_HALF_SCORE,
    FHB_VWAP_FILTER,
    FHB_DELTA_FILTER,
    FHB_SKIP_HIGH_IMPACT,
    FHB_VIX_FILTER,
    FHB_ENTRY_BUF_TICKS,
    FHB_TARGET_R,
    FHB_PARTIAL_R,
)

log = get_logger(__name__)
ET  = pytz.timezone("America/New_York")


# ============================================================
# CONTRACT HELPERS
# ============================================================

def get_front_month_expiry() -> str:
    """
    Return the IBKR expiry string for the current front month.
    Equity index futures roll ~8 trading days before 3rd Friday.
    Update this or just call it dynamically.
    """
    now = datetime.now()
    quarters = [3, 6, 9, 12]
    for q in quarters:
        cal = calendar.monthcalendar(now.year, q)
        fridays = [w[4] for w in cal if w[4] != 0]
        expiry_day = fridays[2]                         # 3rd Friday
        expiry_dt  = datetime(now.year, q, expiry_day)
        roll_dt    = expiry_dt - timedelta(days=10)
        if now <= roll_dt:
            return f"{now.year}{q:02d}"
    return f"{now.year + 1}03"


CONTRACT_EXCHANGE = {
    "ES": "CME",
    "NQ": "CME",
    "GC": "COMEX",
    "RTY": "CME",
}


def make_contract(market: str) -> "Future":
    expiry   = get_front_month_expiry()
    exchange = CONTRACT_EXCHANGE.get(market, "CME")
    return Future(market, expiry, exchange)


# ============================================================
# BAR HELPERS
# ============================================================

def _ibkr_bars_to_df(bars) -> pd.DataFrame:
    """Convert ib_insync BarDataList -> standard OHLCV DataFrame in ET."""
    if not bars:
        return pd.DataFrame()
    rows = []
    for b in bars:
        ts = b.date
        if isinstance(ts, str):
            ts = pd.Timestamp(ts)
        elif not isinstance(ts, pd.Timestamp):
            ts = pd.Timestamp(ts)
        rows.append({
            "Timestamp": ts,
            "Open":      float(b.open),
            "High":      float(b.high),
            "Low":       float(b.low),
            "Close":     float(b.close),
            "Volume":    float(b.volume) if b.volume >= 0 else 0.0,
        })
    df = pd.DataFrame(rows)
    df["Timestamp"] = pd.to_datetime(df["Timestamp"])

    # Localise to ET (IBKR returns US/Eastern for RTH bars when formatDate=1)
    if df["Timestamp"].dt.tz is None:
        df["Timestamp"] = df["Timestamp"].dt.tz_localize("America/New_York",
                                                          ambiguous="NaT",
                                                          nonexistent="NaT")
    else:
        df["Timestamp"] = df["Timestamp"].dt.tz_convert("America/New_York")

    df = df.dropna(subset=["Timestamp"])
    df = df.set_index("Timestamp").sort_index()
    return df


def _request_bars(ib: IB, market: str, bar_size: str,
                  duration: str = "2 D") -> pd.DataFrame:
    """Request historical IBKR bars. Returns empty DataFrame on failure."""
    if not IB_AVAILABLE:
        log.error("ib_insync not available")
        return pd.DataFrame()
    contract = make_contract(market)
    try:
        ib.qualifyContracts(contract)
    except Exception as e:
        log.warning("{m}: contract qualify failed -- {e}", m=market, e=e)

    try:
        bars = ib.reqHistoricalData(
            contract,
            endDateTime   = "",          # up to now
            durationStr   = duration,
            barSizeSetting= bar_size,
            whatToShow    = "TRADES",
            useRTH        = True,
            formatDate    = 1,           # exchange timezone string (ET for ES/NQ)
            timeout       = 30,
        )
        df = _ibkr_bars_to_df(bars)
        log.info("{m}: got {n} {bs} bars from IBKR", m=market, n=len(df), bs=bar_size)
        return df
    except Exception as e:
        log.error("{m}: IBKR historical data failed -- {e}", m=market, e=e)
        return pd.DataFrame()


# ============================================================
# HTF BIAS / REGIME LOADER
# ============================================================

def load_htf_data(market: str, config: dict):
    """
    Load daily HTF bias, regime, and fast_bias for a market.
    Returns (bias_series, regime_series, fast_bias_series).
    Falls back to empty Series on failure.
    """
    empty = pd.Series(dtype=str)
    try:
        raw = download_market(market, "2022-01-01",
                              datetime.now().strftime("%Y-%m-%d"))
        if raw is None or raw.empty:
            return empty, empty, empty
        strat_cfg  = config.get("strategy", config)
        regime_cfg = config.get("regime", strat_cfg)
        df = calculate_indicators(raw, strat_cfg, market)
        df = add_atr_baseline(df)
        df = classify_regimes(df, regime_cfg, market)
        df = add_htf_bias(df, config, market)
        bias       = df["htf_combined_bias"].copy()
        regime     = df["regime"].copy()
        fast_bias  = df["fast_bias"].copy() if "fast_bias" in df.columns else empty.copy()
        bias.index       = pd.to_datetime(bias.index).normalize()
        regime.index     = pd.to_datetime(regime.index).normalize()
        fast_bias.index  = pd.to_datetime(fast_bias.index).normalize()
        log.info("{m}: HTF loaded ({n} days)", m=market, n=len(bias))
        return bias, regime, fast_bias
    except Exception as e:
        log.warning("{m}: HTF load failed -- {e}", m=market, e=e)
        return empty, empty, empty


# ============================================================
# LIVE SIGNAL ENGINE
# ============================================================

class LiveSignalEngine:
    """
    Generates live ORB and FHB signals using IBKR bar data.

    Usage:
        engine = LiveSignalEngine(ib, config, econ_cal, vix_filter, gls_engine)
        engine.load_htf(["ES", "NQ"])

        # At 09:45 ET
        signal = engine.check_orb("ES")

        # At 10:30 ET
        signal = engine.check_fhb("ES")

        # signal dict goes straight to IBKRBridge.submit_signal(signal)
    """

    def __init__(
        self,
        ib:          "IB",
        config:      dict,
        econ_cal     = None,
        vix_filter   = None,
        gls_engine   = None,
    ):
        self.ib         = ib
        self.config     = config

        # ── Load strategy plugin flags from web control panel ──────────────
        # Flags set via http://localhost:8000/control are respected here.
        # If bot_state.json is missing, all flags default to True (safe).
        try:
            state_file = Path(__file__).parent.parent.parent / "dashboard" / "cache" / "bot_state.json"
            if state_file.exists():
                import json as _json
                _state = _json.loads(state_file.read_text(encoding="utf-8"))
                self._flags = _state.get("strategy_flags", {})
            else:
                self._flags = {}
        except Exception:
            self._flags = {}

        def _flag(name: str, default: bool = True) -> bool:
            return bool(self._flags.get(name, default))

        # Apply flags: pass None instead of the object to disable a filter
        self.econ_cal   = econ_cal   if _flag("econ_filter")  else None
        self.vix_filter = vix_filter if _flag("vix_filter")   else None
        self.gls_engine = gls_engine if _flag("gls_gate")     else None

        # Log active configuration
        active_flags = {k: v for k, v in self._flags.items()}
        log.info(
            "LiveSignalEngine init: econ_filter={e} vix_filter={v} "
            "gls_gate={g} htf_bias={h} half_stop={hs} overnight={on}",
            e=_flag("econ_filter"), v=_flag("vix_filter"),
            g=_flag("gls_gate"),   h=_flag("htf_bias_gate"),
            hs=_flag("half_stop"), on=_flag("overnight_carry"),
        )

        self._htf_bias:      dict[str, pd.Series] = {}
        self._htf_regime:    dict[str, pd.Series] = {}
        self._htf_fast_bias: dict[str, pd.Series] = {}

        # ── Load risk mode from bot_state + config ────────────────────────────
        try:
            import yaml as _yaml
            import json as _json2
            _state_path2 = Path(__file__).parent.parent.parent / "dashboard" / "cache" / "bot_state.json"
            _state2      = _json2.loads(_state_path2.read_text(encoding="utf-8")) if _state_path2.exists() else {}
            _cfg_path    = Path(__file__).parent.parent.parent / "config" / "config.yaml"
            _risk_modes  = {}
            if _cfg_path.exists():
                _full_cfg   = _yaml.safe_load(_cfg_path.read_text(encoding="utf-8"))
                _risk_modes = _full_cfg.get("risk_mode", {})
            _active_mode = _state2.get("risk_mode", "medium")
            _mode_cfg    = _risk_modes.get(_active_mode, {})
            self._risk_pct      = float(_mode_cfg.get("risk_per_trade_pct", 1.0))
            self._max_contracts = int(  _mode_cfg.get("max_contracts",       3))
            self._daily_loss_cap= float(_mode_cfg.get("daily_loss_cap_usd",  2500.0))
            self._risk_mode     = _active_mode
            log.info(
                "LiveSignalEngine risk mode: {m} | risk={r}% | max={c}ct | cap=${cap}",
                m=_active_mode, r=self._risk_pct, c=self._max_contracts,
                cap=self._daily_loss_cap,
            )
        except Exception:
            self._risk_pct       = 1.0
            self._max_contracts  = 3
            self._daily_loss_cap = 2500.0
            self._risk_mode      = "medium"

        # ── Consecutive loss + daily P&L tracking ────────────────────────────
        self._consecutive_losses = 0
        self._daily_pnl          = 0.0

    def load_htf(self, markets: list[str]) -> None:
        """Pre-load daily HTF bias + regime + fast_bias for all markets."""
        for m in markets:
            bias, regime, fast_bias = load_htf_data(m, self.config)
            self._htf_bias[m]       = bias
            self._htf_regime[m]     = regime
            self._htf_fast_bias[m]  = fast_bias

    def _htf_today(self, market: str) -> str:
        """Return today's HTF bias string: BULL / BEAR / NEUTRAL."""
        bias = self._htf_bias.get(market, pd.Series(dtype=str))
        if bias.empty:
            return "NEUTRAL"
        today = pd.Timestamp(datetime.now(ET).date())
        prior = bias[bias.index <= today]
        return str(prior.iloc[-1]) if len(prior) > 0 else "NEUTRAL"

    def _fast_bias_today(self, market: str) -> str:
        """Return today's fast (daily EMA10/EMA20) bias: BULL / BEAR / NEUTRAL."""
        fb = self._htf_fast_bias.get(market, pd.Series(dtype=str))
        if fb.empty:
            return "NEUTRAL"
        today = pd.Timestamp(datetime.now(ET).date())
        prior = fb[fb.index <= today]
        return str(prior.iloc[-1]) if len(prior) > 0 else "NEUTRAL"

    def record_trade_result(self, pnl_net: float) -> None:
        """
        Call after each trade closes to update consecutive loss counter and daily P&L.
        The main trading loop (run_paper_trading.py) should call this when IBKR
        reports a fill/close. Consecutive losses >= 3 will pause new signals.
        """
        self._daily_pnl += pnl_net
        if pnl_net < 0:
            self._consecutive_losses += 1
            log.warning(
                "Trade loss recorded: ${p:.0f} | Consecutive losses: {n}",
                p=pnl_net, n=self._consecutive_losses,
            )
        else:
            self._consecutive_losses = 0
            log.info("Trade win recorded: ${p:.0f} | Streak reset", p=pnl_net)

    def reset_daily(self) -> None:
        """Call at EOD (16:00 ET) to reset all intraday counters."""
        self._consecutive_losses = 0
        self._daily_pnl          = 0.0
        log.info("LiveSignalEngine: daily counters reset (EOD)")

    def _check_paused(self, context: str) -> bool:
        """
        Return True if trading should be paused.
        Checks: consecutive_loss_pause flag (>= 3 losses) and daily loss cap.
        """
        if self._flags.get("consecutive_loss_pause", True):
            if self._consecutive_losses >= 3:
                log.warning(
                    "{ctx}: PAUSED — {n} consecutive losses (flag: consecutive_loss_pause)",
                    ctx=context, n=self._consecutive_losses,
                )
                return True
        if self._daily_pnl <= -self._daily_loss_cap:
            log.warning(
                "{ctx}: PAUSED — daily loss cap hit (${pnl:.0f} of ${cap:.0f})",
                ctx=context, pnl=self._daily_pnl, cap=self._daily_loss_cap,
            )
            return True
        return False

    # ── ORB Signal ────────────────────────────────────────────────────────────

    def check_orb(self, market: str) -> Optional[dict]:
        """
        Check for an ORB signal. Call at 09:45 ET.
        Returns signal dict or None.
        """
        if self._check_paused(f"{market} ORB"):
            return None

        df = _request_bars(self.ib, market, "5 mins", "2 D")
        if df.empty:
            log.warning("{m}: ORB -- no 5-min bars from IBKR", m=market)
            return None

        htf_bias_series = self._htf_bias.get(market, pd.Series(dtype=str))
        df_sig = compute_orb_signals(df, market, self.config, htf_bias_series)

        today_et = datetime.now(ET).date()
        today_df = df_sig[df_sig.index.date == today_et]

        long_sigs  = today_df[today_df.get("orb_long_signal",  False) == True]
        short_sigs = today_df[today_df.get("orb_short_signal", False) == True]

        for direction, sig_rows in [("LONG", long_sigs), ("SHORT", short_sigs)]:
            if sig_rows.empty:
                continue
            row = sig_rows.iloc[-1]

            if bool(row.get("orb_htf_blocked", False)):
                log.info("{m}: ORB {d} blocked by HTF bias", m=market, d=direction)
                continue

            # Calculate entry / stop / target
            markets_cfg  = self.config.get("markets", {})
            mkt          = markets_cfg.get(market, {})
            tick_size    = float(mkt.get("tick_size",       0.25))
            slippage_pts = int(  mkt.get("slippage_ticks",  1)) * tick_size
            point_value  = float(mkt.get("point_value",     50.0))

            rh = float(row.get("orb_range_high", 0))
            rl = float(row.get("orb_range_low",  0))
            if rh <= rl or rh == 0:
                continue

            if direction == "LONG":
                entry  = round(rh + slippage_pts, 4)
                stop   = round(rl - slippage_pts, 4)
            else:
                entry  = round(rl - slippage_pts, 4)
                stop   = round(rh + slippage_pts, 4)

            risk   = abs(entry - stop)
            if risk <= 0:
                continue
            target = round(entry + 2.0 * risk * (1 if direction == "LONG" else -1), 4)

            log.info(
                "{m}: ORB {d} signal | entry={e} stop={s} target={t} "
                "range={rh}/{rl}",
                m=market, d=direction, e=entry, s=stop, t=target, rh=rh, rl=rl,
            )
            intraday_cfg = self.config.get("intraday", {})
            risk_pct = (
                float(intraday_cfg.get("nq_intraday_risk_pct", self._risk_pct))
                if market == "NQ" else self._risk_pct
            )
            return {
                "market":        market,
                "strategy":      "ORB",
                "direction":     direction,
                "entry":         entry,
                "stop":          stop,
                "target":        target,
                "size_mult":     1.0,
                "gls_score":     70,    # ORB does not use GLS; default to full size
                "of_score":      0,
                "risk_pct":      risk_pct,
                "max_contracts": self._max_contracts,
                "risk_mode":     self._risk_mode,
            }

        log.info("{m}: No ORB signal today", m=market)
        return None

    # ── FHB Signal ────────────────────────────────────────────────────────────

    def check_fhb(self, market: str) -> Optional[dict]:
        """
        Check for an FHB signal. Call at 10:30 ET.
        Applies the same gates as simulate_fhb_trades():
          - Consecutive loss pause / daily loss cap
          - Skip HIGH econ impact
          - Skip QUIET / CRISIS VIX
          - Skip HIGH_VOL regime
          - Skip RTY in RANGING regime
          - Skip if GLS action == SKIP
          - Skip if VWAP misaligned (FHB_VWAP_FILTER)
          - Half size if delta misaligned (FHB_DELTA_FILTER)
          - Half size if GLS action == HALF_SIZE
          - Fast bias size adjustments (bear early-caution + neutral dampening)
          - NQ BULL+BULL conviction scaling
        Returns signal dict or None.
        """
        if self._check_paused(f"{market} FHB"):
            return None

        df = _request_bars(self.ib, market, "1 hour", "5 D")
        if df.empty:
            log.warning("{m}: FHB -- no 1-hour bars from IBKR", m=market)
            return None

        htf_bias    = self._htf_bias.get(market,      pd.Series(dtype=str))
        htf_regime  = self._htf_regime.get(market,    pd.Series(dtype=str))
        fast_bias_s = self._htf_fast_bias.get(market, pd.Series(dtype=str))
        atr_series  = compute_1h_atr(df, FHB_ATR_PERIOD)

        df_sig = compute_fhb_signals(
            df, market, htf_bias, htf_regime, self.config,
            econ_cal         = self.econ_cal,
            vix_filter       = self.vix_filter,
            gls_engine       = self.gls_engine,
            fast_bias_series = fast_bias_s,
        )

        today_et = datetime.now(ET).date()
        today_df = df_sig[df_sig.index.date == today_et]

        # Find any signal fired today (long or short)
        candidates = []
        for direction, col in [("LONG", "fhb_long_signal"), ("SHORT", "fhb_short_signal")]:
            if col not in today_df.columns:
                continue
            rows = today_df[today_df[col] == True]
            for idx, row in rows.iterrows():
                candidates.append((idx, row, direction))

        if not candidates:
            log.info("{m}: No FHB signal today", m=market)
            return None

        # Use the first signal of the day (matches backtest -- one per day)
        candidates.sort(key=lambda x: x[0])
        sig_idx, row, direction = candidates[0]

        # ── Apply simulation gates (mirrors simulate_fhb_trades) ──────────────
        econ_impact  = str(row.get("fhb_econ_impact",  "NONE"))
        vix_regime   = str(row.get("fhb_vix_regime",   "OPTIMAL"))
        daily_regime = str(row.get("fhb_daily_regime", "TRENDING"))
        gls_score    = int(row.get("fhb_gls_score",    0))
        gls_action   = str(row.get("fhb_gls_action",   "FULL_SIZE"))
        vwap_aligned = bool(row.get("fhb_vwap_aligned",  True))
        delta_aligned= bool(row.get("fhb_delta_aligned", True))
        of_score     = int(row.get("fhb_of_score", 0))

        # HIGH_VOL hard skip (Phase 5D finding)
        if daily_regime == "HIGH_VOL":
            log.info("{m}: FHB skipped -- HIGH_VOL regime", m=market)
            return None

        # RTY RANGING gate: RTY edge only exists in TRENDING/TRANSITIONING
        if market == "RTY" and daily_regime == "RANGING":
            log.info("{m}: FHB skipped -- RTY RANGING regime", m=market)
            return None

        # Econ calendar hard skip
        if FHB_SKIP_HIGH_IMPACT and econ_impact == "HIGH":
            log.info("{m}: FHB skipped -- HIGH econ impact", m=market)
            return None

        # VIX regime skip
        if FHB_VIX_FILTER and vix_regime in ("QUIET", "CRISIS"):
            log.info("{m}: FHB skipped -- VIX={v}", m=market, v=vix_regime)
            return None

        # GLS skip
        if gls_action == "SKIP":
            log.info("{m}: FHB skipped -- GLS={g}", m=market, g=gls_score)
            return None

        # VWAP hard skip
        if FHB_VWAP_FILTER and not vwap_aligned:
            log.info("{m}: FHB skipped -- VWAP misaligned", m=market)
            return None

        # Size multiplier
        size_mult = 1.0
        if gls_action == "HALF_SIZE":
            size_mult *= 0.5
        if FHB_DELTA_FILTER and not delta_aligned:
            size_mult *= 0.5

        # Fast bias size adjustment (mirrors simulate_fhb_trades)
        htf_b_live  = self._htf_today(market)
        fast_b_live = self._fast_bias_today(market)
        if htf_b_live == "BULL" and fast_b_live == "BEAR" and direction == "LONG":
            size_mult *= 0.75
        elif htf_b_live == "NEUTRAL" and fast_b_live == "BEAR" and direction == "LONG":
            size_mult *= 0.5
        elif htf_b_live == "NEUTRAL" and fast_b_live == "BULL" and direction == "SHORT":
            size_mult *= 0.5

        # NQ BULL+BULL selective scaling
        if market == "NQ" and direction == "LONG":
            if htf_b_live == "BULL" and fast_b_live == "BULL":
                size_mult = min(size_mult * 1.5, 1.5)
                log.info("{m}: NQ BULL+BULL boost applied → size_mult={sz}", m=market, sz=size_mult)

        # ── Entry / stop / target ─────────────────────────────────────────────
        markets_cfg  = self.config.get("markets", {})
        mkt          = markets_cfg.get(market, {})
        tick_size    = float(mkt.get("tick_size",       0.25))
        slippage_pts = int(  mkt.get("slippage_ticks",  1)) * tick_size

        range_high = float(row.get("fhb_range_high", 0))
        range_low  = float(row.get("fhb_range_low",  0))
        if range_high <= range_low or range_high == 0:
            log.warning("{m}: FHB invalid range h={h} l={l}", m=market,
                        h=range_high, l=range_low)
            return None

        atr_val = float(atr_series.get(sig_idx, 0))
        if atr_val <= 0:
            log.warning("{m}: FHB ATR=0, cannot size stop", m=market)
            return None

        entry_buf = FHB_ENTRY_BUF_TICKS * tick_size
        if direction == "LONG":
            entry  = round(range_high + entry_buf + slippage_pts, 4)
            stop   = round(entry - FHB_ATR_STOP_MULT * atr_val,   4)
        else:
            entry  = round(range_low  - entry_buf - slippage_pts, 4)
            stop   = round(entry + FHB_ATR_STOP_MULT * atr_val,   4)

        risk   = abs(entry - stop)
        target = round(entry + FHB_TARGET_R * risk * (1 if direction == "LONG" else -1), 4)

        log.info(
            "{m}: FHB {d} signal | entry={e} stop={s} target={t} "
            "atr={a:.2f} GLS={g} OF={o} size={sz}",
            m=market, d=direction, e=entry, s=stop, t=target,
            a=atr_val, g=gls_score, o=of_score, sz=size_mult,
        )

        intraday_cfg = self.config.get("intraday", {})
        fhb_risk_pct = (
            float(intraday_cfg.get("nq_intraday_risk_pct", self._risk_pct))
            if market == "NQ" else self._risk_pct
        )
        return {
            "market":        market,
            "strategy":      "FHB",
            "direction":     direction,
            "entry":         entry,
            "stop":          stop,
            "target":        target,
            "size_mult":     size_mult,
            "gls_score":     gls_score,
            "of_score":      of_score,
            "htf_bias":      htf_b_live,
            "fast_bias":     fast_b_live,
            "risk_pct":      fhb_risk_pct,
            "max_contracts": self._max_contracts,
            "risk_mode":     self._risk_mode,
        }

    # ── GC Mean Reversion Signal ──────────────────────────────────────────────

    def check_gc(self) -> Optional[dict]:
        """
        Check for a GC (Gold) mean-reversion signal. Call at 10:30 ET.
        Inverts the FHB direction: breakout UP -> SHORT fade, DOWN -> LONG fade.
        HTF filter: skip fade if HTF strongly confirms the breakout direction.
        Returns signal dict or None.
        """
        if self._check_paused("GC"):
            return None

        df = _request_bars(self.ib, "GC", "1 hour", "5 D")
        if df.empty:
            log.warning("GC: no 1-hour bars from IBKR")
            return None

        from src.strategy.gc_signal import compute_gc_signals

        htf_bias   = self._htf_bias.get("GC",   pd.Series(dtype=str))
        htf_regime = self._htf_regime.get("GC",  pd.Series(dtype=str))

        df_sig = compute_gc_signals(
            df, "GC", htf_bias, htf_regime, self.config,
            econ_cal=self.econ_cal, vix_filter=self.vix_filter,
        )

        today_et = datetime.now(ET).date()
        today_df = df_sig[df_sig.index.date == today_et]

        for direction, col in [("LONG", "gc_long_signal"), ("SHORT", "gc_short_signal")]:
            if col not in today_df.columns:
                continue
            rows = today_df[today_df[col] == True]
            if rows.empty:
                continue

            row = rows.iloc[0]
            if bool(row.get("gc_htf_blocked", False)):
                log.info("GC: {d} signal blocked by HTF bias", d=direction)
                continue

            markets_cfg  = self.config.get("markets", {})
            mkt_cfg      = markets_cfg.get("GC", {})
            tick_size    = float(mkt_cfg.get("tick_size",       0.10))
            slippage_pts = int(  mkt_cfg.get("slippage_ticks",  1)) * tick_size

            atr_val    = float(row.get("gc_atr",        0))
            range_high = float(row.get("gc_range_high", 0))
            range_low  = float(row.get("gc_range_low",  0))

            if range_high <= range_low or atr_val <= 0:
                log.warning("GC: invalid range h={h} l={l} atr={a}", h=range_high, l=range_low, a=atr_val)
                continue

            gc_cfg    = self.config.get("gc_reversion", {})
            atr_mult  = float(gc_cfg.get("atr_stop_mult", 1.0))
            target_r  = float(gc_cfg.get("target_r",      1.0))
            entry_buf = tick_size  # 1 tick beyond range boundary

            if direction == "LONG":
                entry  = round(range_low  - entry_buf - slippage_pts, 2)
                stop   = round(entry - atr_mult * atr_val, 2)
            else:
                entry  = round(range_high + entry_buf + slippage_pts, 2)
                stop   = round(entry + atr_mult * atr_val, 2)

            risk = abs(entry - stop)
            if risk <= 0:
                continue
            target = round(entry + target_r * risk * (1 if direction == "LONG" else -1), 2)

            log.info(
                "GC: {d} signal | entry={e} stop={s} target={t} atr={a:.2f}",
                d=direction, e=entry, s=stop, t=target, a=atr_val,
            )
            return {
                "market":        "GC",
                "strategy":      "GC_REV",
                "direction":     direction,
                "entry":         entry,
                "stop":          stop,
                "target":        target,
                "size_mult":     1.0,
                "gls_score":     60,
                "of_score":      0,
                "risk_mode":     self._risk_mode,
                "max_contracts": self._max_contracts,
            }

        log.info("GC: No signal today")
        return None
